import type { NextPage } from 'next'
import NextLink from 'next/Link'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className='px-8'>
      <Head>
        <title>Next.js Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-1 flex-col justify-center items-center py-4 min-h-min'>
        <h1 className='m-0 leading-5 text-7xl'>
          Welcome to <a className='text-blue-500 hover:underline' href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className='my-16 leading-6 text-2xl text-center'>
          Get started by editing{' '}
          <code className='code'>pages/index.tsx</code>
        </p>

        <div className='flex justify-center items-center flex-wrap'>
          {/* <Link href="/users">
            <div className={styles.card}>
              <h2>Users &rarr;</h2>
              <p>GET fakeAPI from jsonplaceholder. We have 10 users list.</p>
            </div>
          </Link> */}

          <NextLink href="/character" shallow={true}>
            <div className='m-4 p-6 text-left border-2 rounded-md cursor-pointer hover:text-blue-500 border-blue-500'>
              <h2 className='mb-4 text-2xl'>Character &rarr;</h2>
              <p className='m-0 text-xl leading-6'>GET rickandmortyapi. Characterlist Go!</p>
            </div>
          </NextLink>
        </div>
      </main>
    </div>
  )
}

export default Home
